// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: proto/chat.proto

package pb

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Action int32

const (
	Action_Create Action = 0
	Action_Update Action = 1
	Action_Delete Action = 2
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0: "Create",
		1: "Update",
		2: "Delete",
	}
	Action_value = map[string]int32{
		"Create": 0,
		"Update": 1,
		"Delete": 2,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_chat_proto_enumTypes[0].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_proto_chat_proto_enumTypes[0]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{0}
}

// write chat
type CreateChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       uint64                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Status        []*AnyUserStatus       `protobuf:"bytes,3,rep,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChatRequest) Reset() {
	*x = CreateChatRequest{}
	mi := &file_proto_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatRequest) ProtoMessage() {}

func (x *CreateChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatRequest.ProtoReflect.Descriptor instead.
func (*CreateChatRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{0}
}

func (x *CreateChatRequest) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *CreateChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateChatRequest) GetStatus() []*AnyUserStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type AnyUserStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      uint64                 `protobuf:"varint,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnyUserStatus) Reset() {
	*x = AnyUserStatus{}
	mi := &file_proto_chat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnyUserStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnyUserStatus) ProtoMessage() {}

func (x *AnyUserStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnyUserStatus.ProtoReflect.Descriptor instead.
func (*AnyUserStatus) Descriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{1}
}

func (x *AnyUserStatus) GetMemberId() uint64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *AnyUserStatus) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type CreateChatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateChatResponse) Reset() {
	*x = CreateChatResponse{}
	mi := &file_proto_chat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateChatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateChatResponse) ProtoMessage() {}

func (x *CreateChatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateChatResponse.ProtoReflect.Descriptor instead.
func (*CreateChatResponse) Descriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{2}
}

func (x *CreateChatResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       uint64                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	ChatId        uint64                 `protobuf:"varint,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChatRequest) Reset() {
	*x = DeleteChatRequest{}
	mi := &file_proto_chat_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChatRequest) ProtoMessage() {}

func (x *DeleteChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChatRequest.ProtoReflect.Descriptor instead.
func (*DeleteChatRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{3}
}

func (x *DeleteChatRequest) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *DeleteChatRequest) GetChatId() uint64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

type UpdateChatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       uint64                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	ChatId        uint64                 `protobuf:"varint,2,opt,name=chat_id,json=chatId,proto3" json:"chat_id,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateChatRequest) Reset() {
	*x = UpdateChatRequest{}
	mi := &file_proto_chat_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateChatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateChatRequest) ProtoMessage() {}

func (x *UpdateChatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateChatRequest.ProtoReflect.Descriptor instead.
func (*UpdateChatRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateChatRequest) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *UpdateChatRequest) GetChatId() uint64 {
	if x != nil {
		return x.ChatId
	}
	return 0
}

func (x *UpdateChatRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// write group & member
type CreateGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Desc          string                 `protobuf:"bytes,2,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupRequest) Reset() {
	*x = CreateGroupRequest{}
	mi := &file_proto_chat_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupRequest) ProtoMessage() {}

func (x *CreateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{5}
}

func (x *CreateGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateGroupRequest) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

type DeleteGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       uint64                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGroupRequest) Reset() {
	*x = DeleteGroupRequest{}
	mi := &file_proto_chat_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupRequest) ProtoMessage() {}

func (x *DeleteGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteGroupRequest) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type UpdateGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       uint64                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Desc          string                 `protobuf:"bytes,3,opt,name=desc,proto3" json:"desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateGroupRequest) Reset() {
	*x = UpdateGroupRequest{}
	mi := &file_proto_chat_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateGroupRequest) ProtoMessage() {}

func (x *UpdateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateGroupRequest.ProtoReflect.Descriptor instead.
func (*UpdateGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateGroupRequest) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *UpdateGroupRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateGroupRequest) GetDesc() string {
	if x != nil {
		return x.Desc
	}
	return ""
}

type UpdateRoleUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      uint64                 `protobuf:"varint,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	GroupId       uint64                 `protobuf:"varint,2,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Role          string                 `protobuf:"bytes,3,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRoleUserRequest) Reset() {
	*x = UpdateRoleUserRequest{}
	mi := &file_proto_chat_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRoleUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRoleUserRequest) ProtoMessage() {}

func (x *UpdateRoleUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRoleUserRequest.ProtoReflect.Descriptor instead.
func (*UpdateRoleUserRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateRoleUserRequest) GetMemberId() uint64 {
	if x != nil {
		return x.MemberId
	}
	return 0
}

func (x *UpdateRoleUserRequest) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *UpdateRoleUserRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type AddMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       uint64                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	ListUserId    []*ListUserId          `protobuf:"bytes,2,rep,name=list_user_id,json=listUserId,proto3" json:"list_user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddMemberRequest) Reset() {
	*x = AddMemberRequest{}
	mi := &file_proto_chat_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddMemberRequest) ProtoMessage() {}

func (x *AddMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddMemberRequest.ProtoReflect.Descriptor instead.
func (*AddMemberRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{9}
}

func (x *AddMemberRequest) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *AddMemberRequest) GetListUserId() []*ListUserId {
	if x != nil {
		return x.ListUserId
	}
	return nil
}

type RemoveMemberRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       uint64                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	ListMemberId  []*ListUserId          `protobuf:"bytes,2,rep,name=list_member_id,json=listMemberId,proto3" json:"list_member_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveMemberRequest) Reset() {
	*x = RemoveMemberRequest{}
	mi := &file_proto_chat_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveMemberRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveMemberRequest) ProtoMessage() {}

func (x *RemoveMemberRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveMemberRequest.ProtoReflect.Descriptor instead.
func (*RemoveMemberRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{10}
}

func (x *RemoveMemberRequest) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *RemoveMemberRequest) GetListMemberId() []*ListUserId {
	if x != nil {
		return x.ListMemberId
	}
	return nil
}

type ListUserId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        uint64                 `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserId) Reset() {
	*x = ListUserId{}
	mi := &file_proto_chat_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserId) ProtoMessage() {}

func (x *ListUserId) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserId.ProtoReflect.Descriptor instead.
func (*ListUserId) Descriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{11}
}

func (x *ListUserId) GetUserId() uint64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

type ExitGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       uint64                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExitGroupRequest) Reset() {
	*x = ExitGroupRequest{}
	mi := &file_proto_chat_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExitGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExitGroupRequest) ProtoMessage() {}

func (x *ExitGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExitGroupRequest.ProtoReflect.Descriptor instead.
func (*ExitGroupRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{12}
}

func (x *ExitGroupRequest) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type StatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        bool                   `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusResponse) Reset() {
	*x = StatusResponse{}
	mi := &file_proto_chat_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusResponse) ProtoMessage() {}

func (x *StatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusResponse.ProtoReflect.Descriptor instead.
func (*StatusResponse) Descriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{13}
}

func (x *StatusResponse) GetStatus() bool {
	if x != nil {
		return x.Status
	}
	return false
}

// chat stream
type ChatStreamingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       uint64                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatStreamingRequest) Reset() {
	*x = ChatStreamingRequest{}
	mi := &file_proto_chat_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatStreamingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatStreamingRequest) ProtoMessage() {}

func (x *ChatStreamingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatStreamingRequest.ProtoReflect.Descriptor instead.
func (*ChatStreamingRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{14}
}

func (x *ChatStreamingRequest) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type ChatStreamingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        uint64                 `protobuf:"varint,1,opt,name=member,proto3" json:"member,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Timestamp     string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Action        Action                 `protobuf:"varint,5,opt,name=action,proto3,enum=pb.Action" json:"action,omitempty"`
	ReadStatus    []*AnyUserStatus       `protobuf:"bytes,6,rep,name=readStatus,proto3" json:"readStatus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChatStreamingResponse) Reset() {
	*x = ChatStreamingResponse{}
	mi := &file_proto_chat_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChatStreamingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChatStreamingResponse) ProtoMessage() {}

func (x *ChatStreamingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChatStreamingResponse.ProtoReflect.Descriptor instead.
func (*ChatStreamingResponse) Descriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{15}
}

func (x *ChatStreamingResponse) GetMember() uint64 {
	if x != nil {
		return x.Member
	}
	return 0
}

func (x *ChatStreamingResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ChatStreamingResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ChatStreamingResponse) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *ChatStreamingResponse) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_Create
}

func (x *ChatStreamingResponse) GetReadStatus() []*AnyUserStatus {
	if x != nil {
		return x.ReadStatus
	}
	return nil
}

// status user stream
type StatusStreamingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       uint64                 `protobuf:"varint,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusStreamingRequest) Reset() {
	*x = StatusStreamingRequest{}
	mi := &file_proto_chat_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusStreamingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusStreamingRequest) ProtoMessage() {}

func (x *StatusStreamingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusStreamingRequest.ProtoReflect.Descriptor instead.
func (*StatusStreamingRequest) Descriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{16}
}

func (x *StatusStreamingRequest) GetGroupId() uint64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

type StatusStreamingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Member        uint64                 `protobuf:"varint,1,opt,name=member,proto3" json:"member,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatusStreamingResponse) Reset() {
	*x = StatusStreamingResponse{}
	mi := &file_proto_chat_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatusStreamingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatusStreamingResponse) ProtoMessage() {}

func (x *StatusStreamingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatusStreamingResponse.ProtoReflect.Descriptor instead.
func (*StatusStreamingResponse) Descriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{17}
}

func (x *StatusStreamingResponse) GetMember() uint64 {
	if x != nil {
		return x.Member
	}
	return 0
}

func (x *StatusStreamingResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *StatusStreamingResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

// GetGroup by user
type GetListGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         []*GroupInfo           `protobuf:"bytes,1,rep,name=group,proto3" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetListGroupResponse) Reset() {
	*x = GetListGroupResponse{}
	mi := &file_proto_chat_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetListGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetListGroupResponse) ProtoMessage() {}

func (x *GetListGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetListGroupResponse.ProtoReflect.Descriptor instead.
func (*GetListGroupResponse) Descriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{18}
}

func (x *GetListGroupResponse) GetGroup() []*GroupInfo {
	if x != nil {
		return x.Group
	}
	return nil
}

type GroupInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	LastMessage   string                 `protobuf:"bytes,3,opt,name=last_message,json=lastMessage,proto3" json:"last_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupInfo) Reset() {
	*x = GroupInfo{}
	mi := &file_proto_chat_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupInfo) ProtoMessage() {}

func (x *GroupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_proto_chat_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupInfo.ProtoReflect.Descriptor instead.
func (*GroupInfo) Descriptor() ([]byte, []int) {
	return file_proto_chat_proto_rawDescGZIP(), []int{19}
}

func (x *GroupInfo) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GroupInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GroupInfo) GetLastMessage() string {
	if x != nil {
		return x.LastMessage
	}
	return ""
}

var File_proto_chat_proto protoreflect.FileDescriptor

const file_proto_chat_proto_rawDesc = "" +
	"\n" +
	"\x10proto/chat.proto\x12\x02pb\x1a\x1dutils/validate/validate.proto\x1a\x18utils/google/empty.proto\"\x85\x01\n" +
	"\x11CreateChatRequest\x12\"\n" +
	"\bgroup_id\x18\x01 \x01(\x04B\a\xfaB\x042\x02 \x00R\agroupId\x12!\n" +
	"\amessage\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\amessage\x12)\n" +
	"\x06status\x18\x03 \x03(\v2\x11.pb.AnyUserStatusR\x06status\"D\n" +
	"\rAnyUserStatus\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\x04R\bmemberId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\".\n" +
	"\x12CreateChatResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"Y\n" +
	"\x11DeleteChatRequest\x12\"\n" +
	"\bgroup_id\x18\x01 \x01(\x04B\a\xfaB\x042\x02 \x00R\agroupId\x12 \n" +
	"\achat_id\x18\x02 \x01(\x04B\a\xfaB\x042\x02 \x00R\x06chatId\"|\n" +
	"\x11UpdateChatRequest\x12\"\n" +
	"\bgroup_id\x18\x01 \x01(\x04B\a\xfaB\x042\x02 \x00R\agroupId\x12 \n" +
	"\achat_id\x18\x02 \x01(\x04B\a\xfaB\x042\x02 \x00R\x06chatId\x12!\n" +
	"\amessage\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\amessage\"N\n" +
	"\x12CreateGroupRequest\x12\x1b\n" +
	"\x04name\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\x12\x1b\n" +
	"\x04desc\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04desc\"8\n" +
	"\x12DeleteGroupRequest\x12\"\n" +
	"\bgroup_id\x18\x01 \x01(\x04B\a\xfaB\x042\x02 \x00R\agroupId\"r\n" +
	"\x12UpdateGroupRequest\x12\"\n" +
	"\bgroup_id\x18\x01 \x01(\x04B\a\xfaB\x042\x02 \x00R\agroupId\x12\x1b\n" +
	"\x04name\x18\x02 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04name\x12\x1b\n" +
	"\x04desc\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04desc\"~\n" +
	"\x15UpdateRoleUserRequest\x12$\n" +
	"\tmember_id\x18\x01 \x01(\x04B\a\xfaB\x042\x02 \x00R\bmemberId\x12\"\n" +
	"\bgroup_id\x18\x02 \x01(\x04B\a\xfaB\x042\x02 \x00R\agroupId\x12\x1b\n" +
	"\x04role\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x04role\"h\n" +
	"\x10AddMemberRequest\x12\"\n" +
	"\bgroup_id\x18\x01 \x01(\x04B\a\xfaB\x042\x02 \x00R\agroupId\x120\n" +
	"\flist_user_id\x18\x02 \x03(\v2\x0e.pb.ListUserIdR\n" +
	"listUserId\"o\n" +
	"\x13RemoveMemberRequest\x12\"\n" +
	"\bgroup_id\x18\x01 \x01(\x04B\a\xfaB\x042\x02 \x00R\agroupId\x124\n" +
	"\x0elist_member_id\x18\x02 \x03(\v2\x0e.pb.ListUserIdR\flistMemberId\".\n" +
	"\n" +
	"ListUserId\x12 \n" +
	"\auser_id\x18\x01 \x01(\x04B\a\xfaB\x042\x02 \x00R\x06userId\"6\n" +
	"\x10ExitGroupRequest\x12\"\n" +
	"\bgroup_id\x18\x01 \x01(\x04B\a\xfaB\x042\x02 \x00R\agroupId\"(\n" +
	"\x0eStatusResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\bR\x06status\":\n" +
	"\x14ChatStreamingRequest\x12\"\n" +
	"\bgroup_id\x18\x01 \x01(\x04B\a\xfaB\x042\x02 \x00R\agroupId\"\xda\x01\n" +
	"\x15ChatStreamingResponse\x12\x16\n" +
	"\x06member\x18\x01 \x01(\x04R\x06member\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\x12\"\n" +
	"\x06action\x18\x05 \x01(\x0e2\n" +
	".pb.ActionR\x06action\x121\n" +
	"\n" +
	"readStatus\x18\x06 \x03(\v2\x11.pb.AnyUserStatusR\n" +
	"readStatus\"<\n" +
	"\x16StatusStreamingRequest\x12\"\n" +
	"\bgroup_id\x18\x01 \x01(\x04B\a\xfaB\x042\x02 \x00R\agroupId\"e\n" +
	"\x17StatusStreamingResponse\x12\x16\n" +
	"\x06member\x18\x01 \x01(\x04R\x06member\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\";\n" +
	"\x14GetListGroupResponse\x12#\n" +
	"\x05group\x18\x01 \x03(\v2\r.pb.GroupInfoR\x05group\"R\n" +
	"\tGroupInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12!\n" +
	"\flast_message\x18\x03 \x01(\tR\vlastMessage*,\n" +
	"\x06Action\x12\n" +
	"\n" +
	"\x06Create\x10\x00\x12\n" +
	"\n" +
	"\x06Update\x10\x01\x12\n" +
	"\n" +
	"\x06Delete\x10\x022\xb1\x06\n" +
	"\vChatService\x12;\n" +
	"\n" +
	"CreateChat\x12\x15.pb.CreateChatRequest\x1a\x16.pb.CreateChatResponse\x127\n" +
	"\n" +
	"DeleteChat\x12\x15.pb.DeleteChatRequest\x1a\x12.pb.StatusResponse\x127\n" +
	"\n" +
	"UpdateChat\x12\x15.pb.UpdateChatRequest\x1a\x12.pb.StatusResponse\x129\n" +
	"\vCreateGroup\x12\x16.pb.CreateGroupRequest\x1a\x12.pb.StatusResponse\x129\n" +
	"\vDeleteGroup\x12\x16.pb.DeleteGroupRequest\x1a\x12.pb.StatusResponse\x129\n" +
	"\vUpdateGroup\x12\x16.pb.UpdateGroupRequest\x1a\x12.pb.StatusResponse\x125\n" +
	"\tAddMember\x12\x14.pb.AddMemberRequest\x1a\x12.pb.StatusResponse\x12;\n" +
	"\fRemoveMember\x12\x17.pb.RemoveMemberRequest\x1a\x12.pb.StatusResponse\x125\n" +
	"\tExitGroup\x12\x14.pb.ExitGroupRequest\x1a\x12.pb.StatusResponse\x12?\n" +
	"\x0eUpdateRoleUser\x12\x19.pb.UpdateRoleUserRequest\x1a\x12.pb.StatusResponse\x12F\n" +
	"\rChatStreaming\x12\x18.pb.ChatStreamingRequest\x1a\x19.pb.ChatStreamingResponse0\x01\x12L\n" +
	"\x0fStatusStreaming\x12\x1a.pb.StatusStreamingRequest\x1a\x1b.pb.StatusStreamingResponse0\x01\x12@\n" +
	"\fGetListGroup\x12\x16.google.protobuf.Empty\x1a\x18.pb.GetListGroupResponseB\x05Z\x03/pbb\x06proto3"

var (
	file_proto_chat_proto_rawDescOnce sync.Once
	file_proto_chat_proto_rawDescData []byte
)

func file_proto_chat_proto_rawDescGZIP() []byte {
	file_proto_chat_proto_rawDescOnce.Do(func() {
		file_proto_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_chat_proto_rawDesc), len(file_proto_chat_proto_rawDesc)))
	})
	return file_proto_chat_proto_rawDescData
}

var file_proto_chat_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_proto_chat_proto_goTypes = []any{
	(Action)(0),                     // 0: pb.Action
	(*CreateChatRequest)(nil),       // 1: pb.CreateChatRequest
	(*AnyUserStatus)(nil),           // 2: pb.AnyUserStatus
	(*CreateChatResponse)(nil),      // 3: pb.CreateChatResponse
	(*DeleteChatRequest)(nil),       // 4: pb.DeleteChatRequest
	(*UpdateChatRequest)(nil),       // 5: pb.UpdateChatRequest
	(*CreateGroupRequest)(nil),      // 6: pb.CreateGroupRequest
	(*DeleteGroupRequest)(nil),      // 7: pb.DeleteGroupRequest
	(*UpdateGroupRequest)(nil),      // 8: pb.UpdateGroupRequest
	(*UpdateRoleUserRequest)(nil),   // 9: pb.UpdateRoleUserRequest
	(*AddMemberRequest)(nil),        // 10: pb.AddMemberRequest
	(*RemoveMemberRequest)(nil),     // 11: pb.RemoveMemberRequest
	(*ListUserId)(nil),              // 12: pb.ListUserId
	(*ExitGroupRequest)(nil),        // 13: pb.ExitGroupRequest
	(*StatusResponse)(nil),          // 14: pb.StatusResponse
	(*ChatStreamingRequest)(nil),    // 15: pb.ChatStreamingRequest
	(*ChatStreamingResponse)(nil),   // 16: pb.ChatStreamingResponse
	(*StatusStreamingRequest)(nil),  // 17: pb.StatusStreamingRequest
	(*StatusStreamingResponse)(nil), // 18: pb.StatusStreamingResponse
	(*GetListGroupResponse)(nil),    // 19: pb.GetListGroupResponse
	(*GroupInfo)(nil),               // 20: pb.GroupInfo
	(*emptypb.Empty)(nil),           // 21: google.protobuf.Empty
}
var file_proto_chat_proto_depIdxs = []int32{
	2,  // 0: pb.CreateChatRequest.status:type_name -> pb.AnyUserStatus
	12, // 1: pb.AddMemberRequest.list_user_id:type_name -> pb.ListUserId
	12, // 2: pb.RemoveMemberRequest.list_member_id:type_name -> pb.ListUserId
	0,  // 3: pb.ChatStreamingResponse.action:type_name -> pb.Action
	2,  // 4: pb.ChatStreamingResponse.readStatus:type_name -> pb.AnyUserStatus
	20, // 5: pb.GetListGroupResponse.group:type_name -> pb.GroupInfo
	1,  // 6: pb.ChatService.CreateChat:input_type -> pb.CreateChatRequest
	4,  // 7: pb.ChatService.DeleteChat:input_type -> pb.DeleteChatRequest
	5,  // 8: pb.ChatService.UpdateChat:input_type -> pb.UpdateChatRequest
	6,  // 9: pb.ChatService.CreateGroup:input_type -> pb.CreateGroupRequest
	7,  // 10: pb.ChatService.DeleteGroup:input_type -> pb.DeleteGroupRequest
	8,  // 11: pb.ChatService.UpdateGroup:input_type -> pb.UpdateGroupRequest
	10, // 12: pb.ChatService.AddMember:input_type -> pb.AddMemberRequest
	11, // 13: pb.ChatService.RemoveMember:input_type -> pb.RemoveMemberRequest
	13, // 14: pb.ChatService.ExitGroup:input_type -> pb.ExitGroupRequest
	9,  // 15: pb.ChatService.UpdateRoleUser:input_type -> pb.UpdateRoleUserRequest
	15, // 16: pb.ChatService.ChatStreaming:input_type -> pb.ChatStreamingRequest
	17, // 17: pb.ChatService.StatusStreaming:input_type -> pb.StatusStreamingRequest
	21, // 18: pb.ChatService.GetListGroup:input_type -> google.protobuf.Empty
	3,  // 19: pb.ChatService.CreateChat:output_type -> pb.CreateChatResponse
	14, // 20: pb.ChatService.DeleteChat:output_type -> pb.StatusResponse
	14, // 21: pb.ChatService.UpdateChat:output_type -> pb.StatusResponse
	14, // 22: pb.ChatService.CreateGroup:output_type -> pb.StatusResponse
	14, // 23: pb.ChatService.DeleteGroup:output_type -> pb.StatusResponse
	14, // 24: pb.ChatService.UpdateGroup:output_type -> pb.StatusResponse
	14, // 25: pb.ChatService.AddMember:output_type -> pb.StatusResponse
	14, // 26: pb.ChatService.RemoveMember:output_type -> pb.StatusResponse
	14, // 27: pb.ChatService.ExitGroup:output_type -> pb.StatusResponse
	14, // 28: pb.ChatService.UpdateRoleUser:output_type -> pb.StatusResponse
	16, // 29: pb.ChatService.ChatStreaming:output_type -> pb.ChatStreamingResponse
	18, // 30: pb.ChatService.StatusStreaming:output_type -> pb.StatusStreamingResponse
	19, // 31: pb.ChatService.GetListGroup:output_type -> pb.GetListGroupResponse
	19, // [19:32] is the sub-list for method output_type
	6,  // [6:19] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_proto_chat_proto_init() }
func file_proto_chat_proto_init() {
	if File_proto_chat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_chat_proto_rawDesc), len(file_proto_chat_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_chat_proto_goTypes,
		DependencyIndexes: file_proto_chat_proto_depIdxs,
		EnumInfos:         file_proto_chat_proto_enumTypes,
		MessageInfos:      file_proto_chat_proto_msgTypes,
	}.Build()
	File_proto_chat_proto = out.File
	file_proto_chat_proto_goTypes = nil
	file_proto_chat_proto_depIdxs = nil
}
